### ISSUE TITLE
Is it possible to add background colour for each image?

### ISSUE THREAD

**Issue by szhorvat** [miromannino/Justified-Gallery#169] opened 2016-05-30 06:08 UTC
Is it possible at all to have a background colour "placeholder" for images with Justified Gallery?

I have thumbnails in this format, with height, width and background specified:

    <img src='thumbs/DSC_0490.jpg' width='300', height='200' style='background-color: #7b7975;'>

I use `'waitThumbnailsLoad': false`.  My hope was that the background colour would show before the images get loaded, but this doesn't happen if using Justified Gallery.  Without Justified Gallery it does show correctly.

![image](https://cloud.githubusercontent.com/assets/1212871/15640969/9660680a-263d-11e6-9230-a1f9bd2b3d2c.png)

I am very inexperienced with web technologies and this is really the first time I'm doing something of this complexity.

Is it at all possible to have these single-colour placeholders working while using Justified Gallery?

**Comment by szhorvat** [comment] 2016-05-30 10:21
Finally I found the reason for the background not showing: it is the `opacity: 0;` setting on `.justified-gallery > a`.

With opacity 1, the background will show, but we lose the fade-in animation when images load.

I still don't know how to show the background and fade in the image on top of it.

**Comment by miromannino** [comment] 2016-06-17 16:43
duplicate of #152

**Closed by miromannino** 2016-06-17 16:43 UTC
